### ISSUE TITLE
Add column for NS IP

### ISSUE THREAD

**Issue by stathis** [ProteusCortex/kow-whois-api#18]
A nameserver can have its IP change while retaining the same FQDN.
There should be a NS IP field column imo.

https://github.com/ProteusCortex/kow-whois-api/blob/a4ae20b7d9b022d87cfe08b0e99dc81bc248c574/Models/NameServer.cs#L14

**Comment by ProteusCortex** [comment]
There cannot be a single column for IPs, as there might be multiple addresses per host. However, at 3e1325e84b6d9f0414ba7331e416e3ec8997729d the following has been implemented:
- An `Address` class (and relevant table) that holds IPs.
- A many-to-many relationship between `NameServer` and `Address`, with a `created_at` column in the intermediate table. This will facilitate the creation of a timeline for the IPs of each `NameServer`.
- A many-to-many relationship between `Domain` and `Address`, with a `created_at` column in the intermediate table. This will facilitate the creation of a timeline for the IPs of each `Domain`.

**Comment by ProteusCortex** [comment]
A service to resolve host addresses was created, but I discovered that .NET already offers a nice `Dns` class, which offers the very convenient `GetHostAddresses()` method. This resolves all IPv4 and IPv6 addresses for a given host. Some refactoring needs to be done at this point.

**Comment by ProteusCortex** [comment]
With release [v2.6.1](https://github.com/ProteusCortex/kow-whois-api/releases/tag/v2.6.1) this is now fully implemented.
